version: '3.1'
# source:
# https://hub.docker.com/_/mysql/

services:

  db:
    image: mysql:8
    #restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      #MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Z16ZkfhriDvNGuVC

    volumes:
      - "./db_data:/var/lib/mysql:rw"
      - "./sql:/docker-entrypoint-initdb.d:ro"

    command: --default-authentication-plugin=mysql_native_password

  cli:
    build:
      context: ./cli
    environment:
      MYSQL_HOST: db
      #MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: database
      DBI_USER: dbuser
      MYSQL_USER: dbuser
      USER: dbuser
      MYSQL_PWD: Z16ZkfhriDvNGuVC

    volumes:
      - "./sql:/sql:rw"
    command: /bin/bash

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db # default: "db"
    #restart: always
    ports:
      - 8080:8080
